### ISSUE TITLE
Update User (Set password) : Last 5 password policy doesn`t work

### ISSUE THREAD

**Issue by eberttc** [okta/okta-sdk-nodejs#207]
Hi Team,
We're using endpoint **_{{url}}/api/v1/users/{{userId}}_** with body:
{
  "credentials": {
    "password" : { "value": "newPssword" }
  }
}
to reset password from our backend services.

If We send the same password more than 5 times, it does not apply organization policy **"Your password cannot be any of your last 5 passwords."**
Other policies work as we expected e.g password like "abc" or short password (Peru) return correct okta error (See atachment)
![image](https://user-images.githubusercontent.com/5652850/95522602-1eb53780-0992-11eb-90bd-037cc4ccfc35.png)

**Comment by swiftone** [comment]
@eberttc - Thanks for the report.  To clarify, if you send the same password twice in a row, you expect it will be rejected (because of the policy that it can't be any of the last 5 passwords, and the last password counts as one of the last 5), but the repeated change actually goes through?

**Comment by vijetmahabaleshwar-okta** [comment]
@eberttc - This is an expected behavior. The [Set Password](https://developer.okta.com/docs/reference/api/users/#set-password) is an admin endpoint which sets password without validating existing user credentials. This is typically used by an IT Admin to set a user password (where he can bypass the previously used password policy). But it does enforce the "minimum length", "special characters" and other requirements which you might have which don't depend on previous password value.
To enforce the "Can't use recently used password" policy, you should use the [Change Password](https://developer.okta.com/docs/reference/api/users/#change-password) endpoint which is exposed by the node sdk [here](https://github.com/okta/okta-sdk-nodejs/blob/master/src/models/User.js#L79)

Hope this helps. Let us know if you have any further questions about this.

**Comment by eberttc** [comment]
@swiftone I send same password more than 5 times and "Can't use recently used password" never happens. As @venkateshkatti-okta mentioned ,it is an expected behaviour.
Our scenario is to allow user to reset password  after biometric validation(onfido). Change Password required old password and in this case , user forgot his password.

**Comment by vijetmahabaleshwar-okta** [comment]
@eberttc - Have you checked if [forgot password](https://developer.okta.com/docs/reference/api/users/#forgot-password) or  [reset password](https://developer.okta.com/docs/reference/api/users/#reset-password) works for your use case?
They're exposed in the node sdk [here](https://github.com/okta/okta-sdk-nodejs/blob/master/src/models/User.js#L96) and [here](https://github.com/okta/okta-sdk-nodejs/blob/master/src/models/User.js#L273) respectively.

**Comment by eberttc** [comment]
In both cases you mentioned, users need to answer security question. We want to avoid that so we are going to a second flow with biometric validation with onfido.

**Comment by swiftone** [comment]
@eberttc - as this question has evolved past the SDK in this repo and more towards the underlying API and security architecture, we are not the best team to provide answers.

I suggest reaching out to our support team at developers@okta.com as they have a strong understanding of the variety of use-cases and can suggest the best solutions for your situation.  Feel free to point them at this discussion, and they can (and will) ask us any questions, so you aren't starting from scratch.

**Comment by eberttc** [comment]
Ok, thanks for the support 👍
