### ISSUE TITLE
Collection doesn't implement rate-limiting as per limit header

### ISSUE THREAD

**Issue by JQuezada0** [okta/okta-sdk-nodejs#46]
Collection should wait the appropriate amount of time before fetching the next page as per `X-Rate-Limit-Remaining` header. 

For example, system logs sets the header to `120`. So there are a maximum of 120 requests to the API per minute. `Collection` should thus wait 500ms before fetching the next page, so that per minute only a maximum of 120 requests will be made.

**Comment by gabrielsroka** [comment]
@JQuezada0 Not necessarily:

1. If each request takes 500 ms, then you don't have to wait at all (if you're doing them synchronously-- one at a time). Or if each request takes about 400 ms, then you only have to wait 100 ms per request, etc.
2. You might not want to use all 120 every minute -- e.g., you might want to leave some for someone else.
3. It might make more sense to look at `X-Rate-Limit-Remaining` and when it gets "too low", then wait until it Resets.

from https://developer.okta.com/docs/api/getting_started/rate-limits#check-your-rate-limits-with-oktas-rate-limit-headers
`X-Rate-Limit-Limit` - the rate limit ceiling that is applicable for the current request.
`X-Rate-Limit-Remaining` - the number of requests left for the current rate-limit window.
`X-Rate-Limit-Reset` - the time at which the rate limit will reset, specified in UTC epoch time.

**Comment by robertjd** [comment]
Hi @JQuezada0 , @gabrielsroka , thanks for the comments. I have a PR out that gives you the ability to opt-in to our new rate limiting strategy, which should handle these problems for you.  If you have time to check out the branch of #58 and give it a try, I would really value the feedback!

**Comment by robertjd** [comment]
We've released 1.2.0 which provides a new default request executor, this executor will now wait and retry when 429 errors are encountered.  You can opt-in to the executor by adding it to your client constructor call:

```javascript
const client = new okta.Client({
  requestExecutor: new okta.DefaultRequestExecutor()
  // .. other params  
});
```

For full details on the executor, please see the [Request Executor](https://github.com/okta/okta-sdk-nodejs#request-executor) section of the README.

Please give this a try and open any issues that you find, I would really love your feedback on this new feature!

**Comment by agiles231** [comment]
I have written a solution called proktasy that acts a proxy between Okta REST API clients and Okta. It is easily deployed using Tomcat and resolves all rate limiting issues. Also, an SDK would have a difficult time accounting for rate limiting produced by other applications, even if using the same SDK. proktasy solves that too. Let me know if this does what you want. I know in the previous comment, it looks like this library waits for 429 to be sent. IMHO, this is less than optimal because there are certain administrative tasks on the front end that will also be impacted by rate limiting being triggered.

**Comment by gabrielsroka** [comment]
This is interesting. What is the advantage of rewriting the application to
use your proxy versus rewriting it to look at the rate limit headers and
not make calls when you're when you only have X% of the rate limit left? Or
X calls left?

I understand it of from an abstraction point of view. But in terms of
functionality.

What about apps that can't be written, such as Okta itself?

**Comment by agiles231** [comment]
@gabrielsroka 
The advantage is that if you have two applications using the API, they may not have all information necessary to make the correct call. For example, if you have 10 apps hitting the same endpoint (or same as far as rate limiting is concerned), then each app may have a different number of "remainings". Say apps are a0, ..., a9 and that they believe there to be 14, 13, ..., 5 remaining calls before rate limiting because they all made their calls sequentially. Unfortunately, some of them will still make a call to the endpoint (let's say for pagination) and will trigger a cooldown on that endpoint where the endpoint is completely useless until the reset. Using proktasy as a central gateway to Okta, it has all the information and this wouldn't happen. As for the frontend API hits, you can reserve buffers that proktasy will remain just for this purpose. If you have any other questions, let me know.

**Comment by agiles231** [comment]
@gabrielsroka 
And I forgot to mention, there shouldn't be any rewriting necessary. A client/API only needs to change the base url to point to a proktasy instance. So for instance, if an org deploys proktasy to proktasy.domain.com, then a client can simply replace https://domain.okta.com with https://proktasy.domain.com in all calls. Typically, this should just be a configuration change on the deployed client app.

**Comment by gabrielsroka** [comment]
Oh, that makes sense--it's a proxy. Is this the one?
https://github.com/agiles231/proktasy

**Comment by agiles231** [comment]
@gabrielsroka 
Indeed, that's the one.

**Comment by agiles231** [comment]
@gabrielsroka 
I'm not sure what happened to the last message you sent me. I saw the notification but now I can't find it. Can you resent it?
