### ISSUE TITLE
Docs on MFA use

### ISSUE THREAD

**Issue by andrewvanbeek-okta** [okta/okta-sdk-nodejs#47]
Is there any wiki or docs on the factors api?

**Comment by robertjd** [comment]
HI @andrewvanbeek-okta , the JsDoc for the lib is available here (also linked to from README):

https://developer.okta.com/okta-sdk-nodejs/jsdocs/

Because factors are tried to a user, you would work with a User instance to get their factors:

https://developer.okta.com/okta-sdk-nodejs/jsdocs/User.html#listFactors__anchor

Hope this helps!  More than happy to answer more specific questions about factors.
