### ISSUE TITLE
client.getUser Doesn't Work as Documented

### ISSUE THREAD

**Issue by rdegges** [okta/okta-sdk-nodejs#78]
If I try to retrieve a user by their email address, I get an error. The docs make it appear as if we support this usage:

```javascript
client.getUser('foo@bar.com')
.then(user => {
  console.log(user);
});
```

The error says:

```Error: only absolute urls are supported```

**Comment by rdegges** [comment]
Nevermind. I'm an idiot as usual =p

**Comment by craig-thompson-sb** [comment]
Turns out I'm an idiot as well but some additional information might be good for those who come to the issues to see what they're doing wrong. The error message is relatively unhelpful.

Okta provides the client url as a string, without the protocol section. Make sure whatever you're Client options element is receiving has the full url, especially when using environment variables.

e.g. oktaClient.ts
```
const oktaClient = new Client({
  orgUrl: process.env.OKTA_ORG,
  token: process.env.OKTA_TOKEN
});

export {oktaClient}
```

.env
```
OKTA_ORG=https://my-okta-org.okta.com
```
